const allFreelanceTools = [
   // Graphics & Design
   "Adobe Photoshop",
   "Adobe Illustrator",
   "Figma",
   "Adobe InDesign",
   "Canva",
   "Sketch",
   "Affinity Designer",
   "CorelDRAW",
   "Procreate",
   "Blender",
 
   // Digital Marketing
   "Google Analytics",
   "Google Ads",
   "Facebook Business Suite",
   "Hootsuite",
   "Mailchimp",
   "SEMrush",
   "Ahrefs",
   "HubSpot",
   "Meta Pixel",
   "Yoast SEO",
 
   // Writing & Translation
   "Grammarly",
   "Hemingway Editor",
   "Google Docs",
   "Microsoft Word",
   "Quillbot",
   "Jasper.ai",
   "Deepl",
   "Google Translate",
   "Copyscape",
   "Notion",
   "Scrivener",
   "ChatGPT",
 
   // Video & Animation
   "Adobe Premiere Pro",
   "After Effects",
   "Final Cut Pro",
   "DaVinci Resolve",
   "Camtasia",
   "Doodly",
   "Vyond",
   "CapCut",
   "VN Video Editor",
   "OBS Studio",
   "Audacity",
 
   // Music & Audio
   "FL Studio",
   "Ableton Live",
   "Logic Pro X",
   "GarageBand",
   "Pro Tools",
   "Adobe Audition",
   "Auto-Tune",
   "Melodyne",
   "Splice",
   "Loopcloud",
 
   // Programming & Tech
   "HTML",
   "CSS",
   "JavaScript",
   "React.js",
   "Vue.js",
   "Next.js",
   "Node.js",
   "Express",
   "PHP",
   "Laravel",
   "Python",
   "Django",
   "Flask",
   "WordPress",
   "Git",
   "GitHub",
   "MySQL",
   "MongoDB",
   "PostgreSQL",
   "VS Code",
   "IntelliJ IDEA",
   "Postman",
   "Swagger",
 
   // Business
   "Microsoft Excel",
   "Google Sheets",
   "Notion",
   "Trello",
   "ClickUp",
   "Google Workspace",
   "Slidebean",
   "QuickBooks",
   "Zoho",
   "ChatGPT",
   "Stripe",
   "PayPal",
   "DocuSign",
   "UpLead",
   "Apollo",
   "Calendly",
 
   // AI Services
   "ChatGPT",
   "Gemini",
   "Claude",
   "Midjourney",
   "DALL·E",
   "Leonardo AI",
   "Runway ML",
   "Pika Labs",
   "LangChain",
   "OpenAI API",
   "Hugging Face",
   "TensorFlow",
   "PyTorch",
   "Stable Diffusion",
   "AutoGPT",
   "AgentGPT",
   "Notion AI",
   "ElevenLabs",
 
   // Lifestyle
   "Zoom",
   "Google Meet",
   "MyFitnessPal",
   "Strong",
   "Headspace",
   "Calm",
   "Notion",
   "Loom",
   "Canva",
   "Teachable",
   "Kajabi",
   "Duolingo",
   "WhatsApp",
   "Telegram"
 ];
export default allFreelanceTools; 